version: '2'
services:
  zookeeperdbz:
    image: quay.io/debezium/zookeeper:${DEBEZIUM_VERSION}
    container_name: zookeeperdbz
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

  kafkadbz:
    image: quay.io/debezium/kafka:${DEBEZIUM_VERSION}
    container_name: kafkadbz
    ports:
      - 9092:9092
    links:
      - zookeeperdbz
    env_file:
      - ./env/kafkadbz.env

  mysqldbz:
    image: quay.io/debezium/example-mysql:${DEBEZIUM_VERSION}
    container_name: mysqldbz
    ports:
      - 3306:3306
    env_file:
      - ./env/mysqldbz.env

  elasticdbz:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    container_name: elasticdbz
    ports:
      - "9200:9200"
    env_file:
      - ./env/elasticdbz.env

  connectdbz:
    image: debezium/connect-jdbc-es:${DEBEZIUM_VERSION}
    container_name: connectdbz
    build:
      context: debezium-jdbc-es
      args:
        DEBEZIUM_VERSION: ${DEBEZIUM_VERSION}
    ports:
      - 8083:8083
      - 5005:5005
    links:
      - kafkadbz
      - mysqldbz
      - elasticdbz
    env_file:
      - ./env/connectdbz.env
